-- Create sensor_readings table
CREATE TABLE IF NOT EXISTS sensor_readings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id TEXT NOT NULL,
  pm1_0 NUMERIC NOT NULL,
  pm2_5 NUMERIC NOT NULL,
  pm4_0 NUMERIC NOT NULL,
  pm10 NUMERIC NOT NULL,
  co2 NUMERIC NOT NULL,
  temperature NUMERIC NOT NULL,
  humidity NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Create index for queries sorted by timestamp
CREATE INDEX IF NOT EXISTS idx_sensor_readings_created_at ON sensor_readings (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sensor_readings_device_id_created_at ON sensor_readings (device_id, created_at DESC);

-- Enable Realtime replication for this table
-- Note: If publication does not exist, you can create it or ignore this step if configured via UI.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE sensor_readings;
  ELSE
    CREATE PUBLICATION supabase_realtime FOR TABLE sensor_readings;
  END IF;
END $$;
